/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [16-1:0] M_alu_q;
  reg [6-1:0] M_alu_alufn;
  reg [16-1:0] M_alu_a;
  reg [16-1:0] M_alu_b;
  alu__1 alu (
    .alufn(M_alu_alufn),
    .a(M_alu_a),
    .b(M_alu_b),
    .q(M_alu_q)
  );
  
  reg [15:0] M_register_a_d, M_register_a_q = 1'h0;
  reg [15:0] M_register_b_d, M_register_b_q = 1'h0;
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_2 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_register_b_d = M_register_b_q;
    M_register_a_d = M_register_a_q;
    
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    if (io_dip[16+0+0-:1]) begin
      M_register_a_d[8+7-:8] = io_dip[8+7-:8];
      M_register_a_d[0+7-:8] = io_dip[0+7-:8];
    end else begin
      M_register_b_d[8+7-:8] = io_dip[8+7-:8];
      M_register_b_d[0+7-:8] = io_dip[0+7-:8];
    end
    M_alu_a = M_register_a_q;
    M_alu_b = M_register_b_q;
    M_alu_alufn = io_dip[16+2+5-:6];
    io_led[8+7-:8] = M_alu_q[8+7-:8];
    io_led[0+7-:8] = M_alu_q[0+7-:8];
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_register_a_q <= 1'h0;
      M_register_b_q <= 1'h0;
    end else begin
      M_register_a_q <= M_register_a_d;
      M_register_b_q <= M_register_b_d;
    end
  end
  
endmodule
